## Precision-Recall 的平衡

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets

digits = datasets.load_digits()

X = digits.data
y = digits.target.copy()

y[digits.target == 9] = 1
y[digits.target != 9] = 0

/Users/codingzhe/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/codingzhe/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [4]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_predict = log_reg.predict(X_test)

/Users/codingzhe/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [5]:
from sklearn.metrics import f1_score
f1_score(y_test, y_predict)

0.8674698795180723

In [6]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]])

In [7]:
from sklearn.metrics import precision_score, recall_score

In [8]:
precision_score(y_test, y_predict)

0.9473684210526315

In [9]:
recall_score(y_test, y_predict)

0.8

In [12]:
decision_score = log_reg.decision_function(X_test)

In [13]:
np.min(decision_score)

-85.68612416749173

In [14]:
np.max(decision_score)

19.889606885682948

In [15]:
y_predict_2 = np.array(decision_score >= 5, dtype='int')

In [16]:
confusion_matrix(y_test, y_predict_2)

array([[404,   1],
       [ 21,  24]])

In [17]:
precision_score(y_test, y_predict_2)

0.96

In [18]:
recall_score(y_test, y_predict_2)

0.5333333333333333

In [19]:
y_predict_3 = np.array(decision_score >= -5, dtype='int')

In [20]:
confusion_matrix(y_test, y_predict_3)

array([[390,  15],
       [  5,  40]])

In [21]:
precision_score(y_test, y_predict_3)

0.7272727272727273

In [22]:
recall_score(y_test, y_predict_3)

0.8888888888888888